const tvAccounts = {
    headers: {
        userName: 'Username',
        email: 'Email',
        pass: 'Password',
        role: 'Role user',
        base: 'Database',
        customer: 'Customer title',
    },
    data : [
        {
            id: 0,
            userName: 'tv00700003',
            email: 'tv00700003@tv.by',
            pass: 'hxuhrp',
            role: 'superadmin',
            base: 'tv00700003',
            customer: 'Тюмень',
        },
        {
            id: 1,
            userName: 'Александров Иван',
            email: 'derg10@mail.ru',
            pass: 'hfd8ke',
            role: 'admin',
            base: 'tv00700003',
            customer: 'Тюмень',
        },
        {
            id: 2,
            userName: 'test_Minsk',
            email: 'testminsk@tv.by',
            pass: '123455',
            role: 'user',
            base: 'tv00700003',
            customer: 'Тюмень',
        },

        {
            id: 3,
            userName: 'sd0075',
            email: 'sd0075@sd.by',
            pass: 'f644hw',
            role: 'admin',
            base: 'tv37500075',
            customer: 'Байер',
        },
        {
            id: 4,
            userName: 'Новицкий Владимир Владимирович',
            email: '001@sladograd.by',
            pass: 'xy5qj7',
            role: 'admin',
            base: 'tv37500107',
            customer: 'Сладоград',
        },
        {
            id: 5,
            userName: 'Роскач Татьяна Ивановн',
            email: '007@sladograd.by',
            pass: 'wfga8n',
            role: 'user',
            base: 'tv37500107',
            customer: 'Сладоград',
        },
        {
            id: 6,
            userName: 'Скорый Сергей Викторович',
            email: '004@sladograd.by',
            pass: 'p0wksa',
            role: 'user',
            base: 'tv37500107',
            customer: 'Сладоград',
        },
        {
            id: 7,
            userName: 'Лагун Сергей Степанович',
            email: '005@sladograd.by',
            pass: 'bz1ol4',
            role: 'user',
            base: 'tv37500107',
            customer: 'Сладоград',
        },
        {
            id: 8,
            userName: 'Герасимович Наталья Владимировна',
            email: '703@sladograd.by',
            pass: '6th1bl',
            role: 'user',
            base: 'tv37500107',
            customer: 'Сладоград',
        },
        {
            id: 9,
            userName: 'Попко Марина Константиновна',
            email: '704@sladograd.by',
            pass: '6ladqi',
            role: 'user',
            base: 'tv37500107',
            customer: 'Сладоград',
        },
        {
            id: 10,
            userName: 'Москаленко Игорь Алескандрович',
            email: '705@sladograd.by',
            pass: 's36sm6',
            role: 'user',
            base: 'tv37500107',
            customer: 'Сладоград',
        },
        {
            id: 11,
            userName: 'Долгопалец Екатерина Васильевна',
            email: '707@sladograd.by',
            pass: 'wzbp86',
            role: 'user',
            base: 'tv37500107',
            customer: 'Сладоград',
        },
        {
            id: 12,
            userName: 'sd0110',
            email: 'sd0110@sd.by',
            pass: 'eaa194',
            role: 'admin',
            base: 'tv37500110',
            customer: 'МинГаз',
        },
        {
            id: 13,
            userName: 'sd0110',
            email: 'sd0110@sd.by',
            pass: 'eaa194',
            role: 'admin',
            base: 'tv37500110',
            customer: 'МинГаз',
        },
        {
            id: 14,
            userName: 'sd0110',
            email: 'sd0110@sd.by',
            pass: 'eaa194',
            role: 'admin',
            base: 'tv37500110',
            customer: 'МинГаз',
        },
        {
            id: 15,
            userName: 'sd0110q',
            email: 'sd0110@sd.by',
            pass: 'eaa194',
            role: 'admin',
            base: 'tv37500110',
            customer: 'МинГаз',
        },
        {
            id: 16,
            userName: 'sd01102',
            email: 'sd0110@sd.by',
            pass: 'eaa194',
            role: 'admin',
            base: 'tv37500110',
            customer: 'МинГаз',
        },
        {
            id: 17,
            userName: 'sd0110123',
            email: 'sd01103@sd.by',
            pass: 'eaa194',
            role: 'admin',
            base: 'tv37500110',
            customer: 'МинГаз',
        },
        {
            id: 18,
            userName: 'sd0110',
            email: 'sd0110@sd.by',
            pass: 'eaa194',
            role: 'admin',
            base: 'tv37500110',
            customer: 'МинГаз',
        },
        {
            id: 19,
            userName: 'sd0112310',
            email: 'sd0110@sd.by',
            pass: 'eaa194',
            role: 'admin',
            base: 'tv37500110',
            customer: 'МинГаз',
        },
        {
            id: 20,
            userName: 'sd0112310',
            email: 'sd0110123@sd.by',
            pass: 'eaa194',
            role: 'admin',
            base: 'tv37500110',
            customer: 'МинГаз',
        },
        {
            id: 21,
            userName: 's123d0110',
            email: 'sd1230110@sd.by',
            pass: 'eaa194',
            role: 'admin',
            base: 'tv37500110',
            customer: 'МинГаз',
        },
        {
            id: 22,
            userName: '123sd0110',
            email: 'sd1230110@sd.by',
            pass: 'eaa194',
            role: 'admin',
            base: 'tv37500110',
            customer: 'МинГаз',
        },
        {
            id: 23,
            userName: 'sd0110',
            email: 'sd0110@sd.by',
            pass: 'eaa194',
            role: 'admin',
            base: 'tv37500110',
            customer: 'МинГаз',
        },
        {
            id: 24,
            userName: 'sd0110',
            email: 'sd0110@sd.by',
            pass: 'eaa194',
            role: 'admin',
            base: 'tv37500110',
            customer: 'МинГаз',
        },
        {
            id: 25,
            userName: 'sd0110',
            email: 'sd0110@sd.by',
            pass: 'eaa194',
            role: 'admin',
            base: 'tv37500110',
            customer: 'МинГаз',
        },
        {
            id: 26,
            userName: 'sd0110',
            email: 'sd0110@sd.by',
            pass: 'eaa194',
            role: 'admin',
            base: 'tv37500110',
            customer: 'МинГаз',
        },
        {
            id: 27,
            userName: 'sd0110',
            email: 'sd0110@sd.by',
            pass: 'eaa194',
            role: 'admin',
            base: 'tv37500110',
            customer: 'МинГаз',
        },
        {
            id: 28,
            userName: 'sd0110',
            email: 'sd0110@sd.by',
            pass: 'eaa194',
            role: 'admin',
            base: 'tv37500110',
            customer: 'МинГаз',
        },
        {
            id: 29,
            userName: 'sd0110',
            email: 'sd0110@sd.by',
            pass: 'eaa194',
            role: 'admin',
            base: 'tv37500110',
            customer: 'МинГаз',
        },
        {
            id: 30,
            userName: 'sd0110',
            email: 'sd0110@sd.by',
            pass: 'eaa194',
            role: 'admin',
            base: 'tv37500110',
            customer: 'МинГаз',
        },
        {
            id: 31,
            userName: 'sd0110',
            email: 'sd0110@sd.by',
            pass: 'eaa194',
            role: 'admin',
            base: 'tv37500110',
            customer: 'МинГаз',
        },
        {
            id: 32,
            userName: 'sd0110',
            email: 'sd0110@sd.by',
            pass: 'eaa194',
            role: 'admin',
            base: 'tv37500110',
            customer: 'МинГаз',
        },
        {
            id: 33,
            userName: 'sd0110',
            email: 'sd0110@sd.by',
            pass: 'eaa194',
            role: 'admin',
            base: 'tv37500110',
            customer: 'МинГаз',
        },
        {
            id: 34,
            userName: 'sd0110',
            email: 'sd0110@sd.by',
            pass: 'eaa194',
            role: 'admin',
            base: 'tv37500110',
            customer: 'МинГаз',
        },
        {
            id: 35,
            userName: 'sd0110',
            email: 'sd0110@sd.by',
            pass: 'eaa194',
            role: 'admin',
            base: 'tv37500110',
            customer: 'МинГаз',
        },

    ]
};

export default tvAccounts;

